import java.awt.JobAttributes;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Oscardo
 */
public class formDistriFarmaApp extends javax.swing.JFrame {

    /**
     * Creates new form formDistriFarmaApp
     */
    public formDistriFarmaApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgDistruidores = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jlblNombreMedicamento = new javax.swing.JLabel();
        jtxtNombreMedicamento = new javax.swing.JTextField();
        jcbTipoMedicamento = new javax.swing.JComboBox<>();
        jlblNombreMedicamento1 = new javax.swing.JLabel();
        jtxtCantidad = new javax.swing.JTextField();
        jlblTipoMedicamento1 = new javax.swing.JLabel();
        jlblNombreMedicamento2 = new javax.swing.JLabel();
        jrbDistribuidor3 = new javax.swing.JRadioButton();
        jrbDistribuidor1 = new javax.swing.JRadioButton();
        jrbDistribuidor2 = new javax.swing.JRadioButton();
        jlblNombreMedicamento3 = new javax.swing.JLabel();
        jBuscar1 = new javax.swing.JButton();
        jBorrar = new javax.swing.JButton();
        jckFamaciaSecundaria = new javax.swing.JCheckBox();
        jckFamaciaPrincipal = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DistriFarma Applications");

        jlblNombreMedicamento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblNombreMedicamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblNombreMedicamento.setText("Cantidad del Medicamento");
        jlblNombreMedicamento.setToolTipText("Valido solo de 1 a 100 unidades");
        jlblNombreMedicamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jtxtNombreMedicamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jcbTipoMedicamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbTipoMedicamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "analgésico", "analéptico", "anestésico", "antiácido", "antidepresivo", "antibióticos" }));

        jlblNombreMedicamento1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblNombreMedicamento1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblNombreMedicamento1.setText("Nombre del Medicamento");
        jlblNombreMedicamento1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jtxtCantidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCantidad.setToolTipText("Valido solo de 1 a 100 unidades");

        jlblTipoMedicamento1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblTipoMedicamento1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTipoMedicamento1.setText("Tipo del Medicamento");
        jlblTipoMedicamento1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jlblNombreMedicamento2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblNombreMedicamento2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblNombreMedicamento2.setText("Distribuidor farmacéutico");
        jlblNombreMedicamento2.setToolTipText("");
        jlblNombreMedicamento2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bgDistruidores.add(jrbDistribuidor3);
        jrbDistribuidor3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jrbDistribuidor3.setText("Cemefar");
        jrbDistribuidor3.setToolTipText("Cemefar");

        bgDistruidores.add(jrbDistribuidor1);
        jrbDistribuidor1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jrbDistribuidor1.setText("Cofarma");
        jrbDistribuidor1.setToolTipText("Cofarma");

        bgDistruidores.add(jrbDistribuidor2);
        jrbDistribuidor2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jrbDistribuidor2.setText("Empsephar ");
        jrbDistribuidor2.setToolTipText("Empsephar ");

        jlblNombreMedicamento3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblNombreMedicamento3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblNombreMedicamento3.setText("Sucursal de la farmacia");
        jlblNombreMedicamento3.setToolTipText("sucursal de la farmacia");
        jlblNombreMedicamento3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jBuscar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBuscar1.setText("Buscar Información");
        jBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscar1ActionPerformed(evt);
            }
        });

        jBorrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBorrar.setText("Borrar");
        jBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBorrarActionPerformed(evt);
            }
        });

        jckFamaciaSecundaria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jckFamaciaSecundaria.setText("Farmacia Secundaría");

        jckFamaciaPrincipal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jckFamaciaPrincipal.setText("Farmacia Principal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jckFamaciaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblTipoMedicamento1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbDistribuidor2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jlblNombreMedicamento, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                                .addComponent(jtxtNombreMedicamento))
                            .addComponent(jcbTipoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbDistribuidor1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbDistribuidor3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBuscar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlblNombreMedicamento2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblNombreMedicamento3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jckFamaciaSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jlblNombreMedicamento1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addGap(14, 14, 14)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jtxtNombreMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblTipoMedicamento1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbTipoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblNombreMedicamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblNombreMedicamento2)
                .addGap(15, 15, 15)
                .addComponent(jrbDistribuidor1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbDistribuidor2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbDistribuidor3)
                .addGap(18, 18, 18)
                .addComponent(jlblNombreMedicamento3)
                .addGap(29, 29, 29)
                .addComponent(jckFamaciaPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jckFamaciaSecundaria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBorrar)
                    .addComponent(jBuscar1))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(jlblNombreMedicamento1)
                    .addContainerGap(437, Short.MAX_VALUE)))
        );

        jlblNombreMedicamento.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBorrarActionPerformed
        int resp = JOptionPane.showConfirmDialog(null , "¿Desea borrar la información cargada?", "Borrar", 
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.ERROR_MESSAGE);
        if(resp == JOptionPane.YES_OPTION){
            jtxtNombreMedicamento.setText("");
            jtxtCantidad.setText("");
            jcbTipoMedicamento.setSelectedIndex(1);
            bgDistruidores.clearSelection();
            jckFamaciaPrincipal.setSelected(false);
            jckFamaciaSecundaria.setSelected(false);
        }
    }//GEN-LAST:event_jBorrarActionPerformed

    private void jBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscar1ActionPerformed
        if(guardar_informacion(evt)){
            Pedido ped = new Pedido();
            ped.setLocation(500, 200);
            ped.llevar_pedido(NombreMedicamento, Cantidad, Distribuidor, TipoMedicamento, Famacia, opcFarmacia);
            ped.setVisible(true);
        }
    }//GEN-LAST:event_jBuscar1ActionPerformed

    protected boolean guardar_informacion(java.awt.event.ActionEvent evt){
        if(jtxtNombreMedicamento.getText().isEmpty() == true){
                util.Mensaje("No debe estar vacio", "Nombre Medicamento", 3);
                return rpt;
            }
        if(jtxtNombreMedicamento.getText().length() >= 30){
                util.Mensaje("No se permite un medicamento con esa extensión, máximo son 30 caractéres", "Nombre Medicamento", 3);
                return rpt;
            }
        try {
            if(jtxtCantidad.getText().isEmpty() == true){
                util.Mensaje("No debe estar vacio", "Cantidad", 3);
                return rpt;
            }
            Cantidad = Integer.parseInt(jtxtCantidad.getText());
            Cantidad = Math.abs(Cantidad);
            
            if(jcbTipoMedicamento.getSelectedIndex() == -1){
                util.Mensaje("Debe seleccionar algún valor", "Tipo de Medicamento", 3);
                return rpt;
            }
            if(jrbDistribuidor1.isSelected() == false && 
               jrbDistribuidor2.isSelected() == false &&
               jrbDistribuidor3.isSelected() == false){
                util.Mensaje("Debe seleccionar un distribuidor", "Distribuidor", 3);
                return rpt;
            }
            
            if(jrbDistribuidor1.isSelected()) Distribuidor = jrbDistribuidor1.getText();
            if(jrbDistribuidor2.isSelected()) Distribuidor = jrbDistribuidor2.getText();
            if(jrbDistribuidor3.isSelected()) Distribuidor = jrbDistribuidor3.getText();
            
            if(jckFamaciaPrincipal.isSelected() == false && jckFamaciaSecundaria.isSelected() == false){
                util.Mensaje("Debe seleccionar alguna farmacia", "Farmacia", 3);
                return rpt;
            }else if(jckFamaciaPrincipal.isSelected() == true && jckFamaciaSecundaria.isSelected() == false){
                Famacia = "Farmacia Principal";
                opcFarmacia = 1;
            }else if(jckFamaciaPrincipal.isSelected() == false && jckFamaciaSecundaria.isSelected() == true){
                Famacia = "Farmacia Secundaria";
                opcFarmacia = 2;
            }else{
                Famacia = "Farmacia Principal y Secundaria";
                opcFarmacia = 3;
            }
            
            NombreMedicamento = jtxtNombreMedicamento.getText();
            TMedicamento = jcbTipoMedicamento.getSelectedItem();
            TipoMedicamento = String.valueOf(TMedicamento);
            rpt = true;
            
            } catch (Exception e) {
                System.err.print("Error: " + e.getMessage() + " - StackTrace: " + e.getStackTrace().toString());
                JOptionPane.showConfirmDialog(this, "Se ha cometido un error en la conversión de cadena a números");
                rpt = false;
                return rpt;
            }
        return rpt;
    }
    
    Utils util = new Utils();
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formDistriFarmaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formDistriFarmaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formDistriFarmaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formDistriFarmaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formDistriFarmaApp().setVisible(true);
            }
        });
    }

    public String NombreMedicamento = "";
    public int Cantidad = 0;
    public Object TMedicamento = null;
    public String TipoMedicamento = null;
    public String Famacia = "";
    public String Distribuidor = "";
    public boolean rpt = false;
    public int opcFarmacia = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgDistruidores;
    private javax.swing.JButton jBorrar;
    private javax.swing.JButton jBuscar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcbTipoMedicamento;
    private javax.swing.JCheckBox jckFamaciaPrincipal;
    private javax.swing.JCheckBox jckFamaciaSecundaria;
    private javax.swing.JLabel jlblNombreMedicamento;
    private javax.swing.JLabel jlblNombreMedicamento1;
    private javax.swing.JLabel jlblNombreMedicamento2;
    private javax.swing.JLabel jlblNombreMedicamento3;
    private javax.swing.JLabel jlblTipoMedicamento1;
    private javax.swing.JRadioButton jrbDistribuidor1;
    private javax.swing.JRadioButton jrbDistribuidor2;
    private javax.swing.JRadioButton jrbDistribuidor3;
    private javax.swing.JTextField jtxtCantidad;
    private javax.swing.JTextField jtxtNombreMedicamento;
    // End of variables declaration//GEN-END:variables
}
