/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Oscardo
 */
public class Pedido extends javax.swing.JFrame {

    /**
     * Creates new form Pedido
     */
    public Pedido() {
        initComponents();
    }

    /**
     *
     *   «Pedido al distribuidor D» donde D es el distribuidor seleccionado previamente. Esto aparecerá como el título de la ventana (JFrame).
     *   Texto con el medicamento a pedir: «X unidades del T M» donde X es el número de unidades, T es el tipo de medicamento y M el nombre el medicamento (JLabel). Por ejemplo: 10 unidades del antibiótico amoxicilina.
     *   Texto con la dirección de la farmacia a donde enviarlo: «Para la farmacia situada en D» donde D es la dirección de la farmacia (JLabel). Para la farmacia Principal la dirección es Calle de la Rosa n. 28 para la secundaria es Calle Alcazabilla n. 3. Por ejemplo: «Para la farmacia situada en Calle de la Rosa n.28 y para la situada en Calle Alcazabilla n.3».
     *   Además, esta segunda ventana contendrá dos botones (ambos JButton) uno para cancelar el pedido, que cierra la ventana y otro para enviar el pedido. Este envío de pedido lo simularemos con un mensaje por pantalla «System.out.println» («Pedido enviado»).
     *   
     * @param Dato_NombreMedicamento
     * @param Dato_Cantidad
     * @param Dato_Distribuidor
     * @param Dato_TipoMedicamento
     * @param Dato_Famacia
     * @param opcionFarmacia
     */
    public void llevar_pedido(String Dato_NombreMedicamento, int Dato_Cantidad, String Dato_Distribuidor, String Dato_TipoMedicamento, String Dato_Farmacia, int opcionFarmacia){
        NombreMedicamento = Dato_NombreMedicamento;
        Cantidad = Dato_Cantidad;
        Distribuidor = Dato_Distribuidor;
        TipoMedicamento = Dato_TipoMedicamento;
        Farmacia = Dato_Farmacia;
        
        jlblPedido.setText("Pedido al distribuidor: " + Distribuidor);
        String unidades = String.valueOf(Dato_Cantidad) + " Unidades del tipo " + TipoMedicamento + " de " + NombreMedicamento;
        jlbMedicamento.setText(unidades);
        
        String direccion = "";
        switch(opcionFarmacia)
        {
            case 1: direccion = "Para la farmacia situada en Calle de la Rosa n. 28"; break;
            case 2: direccion = "Para la farmacia situada en Calle Alcazabilla n. 3."; break;
            case 3: direccion = "Para la farmacia situada en las Calle de la Rosa n. 28 y para la situada en Calle Alcazabilla n. 3."; break;
            default: direccion = "Para la farmacia situada en las Calle de la Rosa n. 28 y para la situada en Calle Alcazabilla n. 3."; break;
        }
        jlbSucursal.setText(direccion);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbMedicamento = new javax.swing.JLabel();
        jlblPedido = new javax.swing.JLabel();
        jlbSucursal = new javax.swing.JLabel();
        jbtnCancelar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setTitle("Entrega Pedido");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(200, 200));
        setType(java.awt.Window.Type.POPUP);

        jlbMedicamento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbMedicamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbMedicamento.setText("jLabel1");

        jlblPedido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlblPedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblPedido.setText("jLabel1");

        jlbSucursal.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jlbSucursal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbSucursal.setText("jLabel1");

        jbtnCancelar.setText("Cancelar de Pedido");
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });

        jButton2.setText("Envio de Pedido");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(jbtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jlbMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jlbSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jlblPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jlblPedido)
                .addGap(29, 29, 29)
                .addComponent(jlbMedicamento)
                .addGap(18, 18, 18)
                .addComponent(jlbSucursal)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCancelar)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Utils util = new Utils();
        int envio = util.Mensaje("Pedido enviado", Farmacia, 1);
        if(envio == 0){
            System.out.println("Pedido enviado");
            iniciar();
        }
        else{
            System.out.println("Envio Cancelado");
        }
        Borrar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Borrar(){
        this.setVisible(false);
    }
    
    private void iniciar(){
        new formDistriFarmaApp().setVisible(true);
    }
    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        // TODO add your handling code here:
        Utils util = new Utils();
        int cancela = util.Mensaje("Cancelación de enviado", Farmacia, 3);
        //si
        if(cancela == 0){
            System.out.println("Cancelado el enviado");
            Borrar();
        }
        //no
        else if(cancela == 1){
            System.out.println("espera del enviado");
        }
        else if(cancela == 2){
            System.out.println("Cancelado el enviado");
        }
        
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedido().setVisible(true);
            }
        });
    }
    
    private String NombreMedicamento = "";
    private int Cantidad = 0; 
    private String Distribuidor = "";
    private String TipoMedicamento = "";
    private String Farmacia = "";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JLabel jlbMedicamento;
    private javax.swing.JLabel jlbSucursal;
    private javax.swing.JLabel jlblPedido;
    // End of variables declaration//GEN-END:variables
}
